import { ICodeSystem } from '../../../app/models/codeSystems';

export const qualifications: ICodeSystem[] = [
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'AA',
    display: 'Associate of Arts',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'AAS',
    display: 'Associate of Applied Science',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'ABA',
    display: 'Associate of Business Administration',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'AE',
    display: 'Associate of Engineering',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'AS',
    display: 'Associate of Science',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'BA',
    display: 'Bachelor of Arts',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'BBA',
    display: 'Bachelor of Business Administration',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'BE',
    display: 'Bachelor or Engineering',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'BFA',
    display: 'Bachelor of Fine Arts',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'BN',
    display: 'Bachelor of Nursing',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'BS',
    display: 'Bachelor of Science',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'BSL',
    display: 'Bachelor of Science - Law',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'BSN',
    display: 'Bachelor on Science - Nursing',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'BT',
    display: 'Bachelor of Theology',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'CANP',
    display: 'Certified Adult Nurse Practitioner',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'CER',
    display: 'Certificate',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'CMA',
    display: 'Certified Medical Assistant',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'CNM',
    display: 'Certified Nurse Midwife',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'CNP',
    display: 'Certified Nurse Practitioner',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'CNS',
    display: 'Certified Nurse Specialist',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'CPNP',
    display: 'Certified Pediatric Nurse Practitioner',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'CRN',
    display: 'Certified Registered Nurse',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'CTR',
    display: 'Certified Tumor Registrar',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'DBA',
    display: 'Doctor of Business Administration',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'DED',
    display: 'Doctor of Education',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'DIP',
    display: 'Diploma',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'DO',
    display: 'Doctor of Osteopathy',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'EMT',
    display: 'Emergency Medical Technician',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'EMTP',
    display: 'Emergency Medical Technician - Paramedic',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'FPNP',
    display: 'Family Practice Nurse Practitioner',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'HS',
    display: 'High School Graduate',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'JD',
    display: 'Juris Doctor',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'MA',
    display: 'Master of Arts',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'MBA',
    display: 'Master of Business Administration',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'MCE',
    display: 'Master of Civil Engineering',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'MD',
    display: 'Doctor of Medicine',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'MDA',
    display: 'Medical Assistant',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'MDI',
    display: 'Master of Divinity',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'ME',
    display: 'Master of Engineering',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'MED',
    display: 'Master of Education',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'MEE',
    display: 'Master of Electrical Engineering',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'MFA',
    display: 'Master of Fine Arts',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'MME',
    display: 'Master of Mechanical Engineering',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'MS',
    display: 'Master of Science',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'MSL',
    display: 'Master of Science - Law',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'MSN',
    display: 'Master of Science - Nursing',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'MT',
    display: 'Medical Technician',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'MTH',
    display: 'Master of Theology',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'NG',
    display: 'Non-Graduate',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'NP',
    display: 'Nurse Practitioner',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'PA',
    display: 'Physician Assistant',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'PHD',
    display: 'Doctor of Philosophy',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'PHE',
    display: 'Doctor of Engineering',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'PHS',
    display: 'Doctor of Science',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'PN',
    display: 'Advanced Practice Nurse',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'PharmD',
    display: 'Doctor of Pharmacy',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'RMA',
    display: 'Registered Medical Assistant',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'RN',
    display: 'Registered Nurse',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'RPH',
    display: 'Registered Pharmacist',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'SEC',
    display: 'Secretarial Certificate',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0360|2.7',
    type: 'qualification',
    code: 'TS',
    display: 'Trade School Graduate',
  },
];
