import { ICodeSystem } from '../../../app/models';

export const relationships: ICodeSystem[] = [
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'SEL',
    display: 'Self',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'SPO',
    display: 'Spouse',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'DOM',
    display: 'Life partner',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'CHD',
    display: 'Child',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'GCH',
    display: 'Grandchild',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'NCH',
    display: 'Natural child',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'SCH',
    display: 'Stepchild',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'FCH',
    display: 'Foster child',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'DEP',
    display: 'Handicapped dependent',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'WRD',
    display: 'Ward of court',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'PAR',
    display: 'Parent',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'MTH',
    display: 'Mother',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'FTH',
    display: 'Father',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'CGV',
    display: 'Care giver',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'GRD',
    display: 'Guardian',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'GRP',
    display: 'Grandparent',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'EXF',
    display: 'Extended family',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'SIB',
    display: 'Sibling',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'BRO',
    display: 'Brother',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'SIS',
    display: 'Sister',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'FND',
    display: 'Friend',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'OAD',
    display: 'Other adult',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'EME',
    display: 'Employee',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'EMR',
    display: 'Employer',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'ASC',
    display: 'Associate',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'EMC',
    display: 'Emergency contact',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'OWN',
    display: 'Owner',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'TRA',
    display: 'Trainer',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'MGR',
    display: 'Manager',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'NON',
    display: 'None',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'UNK',
    display: 'Unknown',
  },
  {
    system: 'http://terminology.hl7.org/CodeSystem/v2-0063',
    type: 'relationship',
    code: 'OTH',
    display: 'Other',
  },
];
