export const Appointment = {
    "type":"object",
    "required":[
        "appointmentType",
        "basedOn",
        "comment",
        "created",
        "description",
        "end",
        "id",
        "meta",
        "participant",
        "priority",
        "reasonReference",
        "resourceType",
        "serviceCategory",
        "serviceType",
        "specialty",
        "start",
        "status",
        "text"
    ],
    "properties":{
        "resourceType":{
            "type":"string",
            "minLength":1
        },
        "id":{
            "type":"string",
            "minLength":1
        },
        "text":{
            "$ref":"#/definitions/Account_text"
        },
        "status":{
            "type":"string",
            "minLength":1
        },
        "serviceCategory":{
            "type":"array",
            "uniqueItems":true,
            "items":{
                "$ref":"#/definitions/AdverseEvent_category"
            },
            "minItems":1
        },
        "serviceType":{
            "type":"array",
            "uniqueItems":true,
            "items":{
                "$ref":"#/definitions/Appointment_serviceType"
            },
            "minItems":1
        },
        "specialty":{
            "type":"array",
            "uniqueItems":true,
            "items":{
                "$ref":"#/definitions/AdverseEvent_category"
            },
            "minItems":1
        },
        "appointmentType":{
            "$ref":"#/definitions/ActivityDefinition_valueCodeableConcept"
        },
        "reasonReference":{
            "type":"array",
            "uniqueItems":true,
            "items":{
                "$ref":"#/definitions/Account_subject"
            },
            "minItems":1
        },
        "priority":{
            "type":"number"
        },
        "description":{
            "type":"string",
            "minLength":1
        },
        "start":{
            "type":"string",
            "minLength":1
        },
        "end":{
            "type":"string",
            "minLength":1
        },
        "created":{
            "type":"string",
            "minLength":1
        },
        "comment":{
            "type":"string",
            "minLength":1
        },
        "basedOn":{
            "type":"array",
            "uniqueItems":true,
            "items":{
                "$ref":"#/definitions/Account_coverage"
            },
            "minItems":1
        },
        "participant":{
            "type":"array",
            "uniqueItems":true,
            "items":{
                "$ref":"#/definitions/Appointment_participant"
            },
            "minItems":1
        },
        "meta":{
            "$ref":"#/definitions/Account_meta"
        }
    },
    "description":""
}

export const Appointment_participant = {
    "required":[
        "required",
        "status"
    ],
    "properties":{
        "type":{
            "type":"array",
            "uniqueItems":true,
            "items":{
                "$ref":"#/definitions/ActivityDefinition_jurisdiction"
            },
            "minItems":1
        },
        "actor":{
            "$ref":"#/definitions/Account_subject"
        },
        "required":{
            "type":"string",
            "minLength":1
        },
        "status":{
            "type":"string",
            "minLength":1
        }
    }
}

export const Appointment_serviceType = {
    "properties":{
        "coding":{
            "type":"array",
            "uniqueItems":true,
            "items":{
                "$ref":"#/definitions/Appointment_coding"
            },
            "minItems":1
        }
    }
}

export const Appointment_coding = {
    "required":[
        "code",
        "display"
    ],
    "properties":{
        "code":{
            "type":"string",
            "minLength":1
        },
        "display":{
            "type":"string",
            "minLength":1
        }
    }
}