export const Encounter = {
    "type":"object",
    "required":[
        "class",
        "id",
        "meta",
        "resourceType",
        "status",
        "subject",
        "text"
    ],
    "properties":{
        "resourceType":{
            "type":"string",
            "minLength":1
        },
        "id":{
            "type":"string",
            "minLength":1
        },
        "text":{
            "$ref":"#/definitions/Account_text"
        },
        "status":{
            "type":"string",
            "minLength":1
        },
        "class":{
            "$ref":"#/definitions/Account_type_coding"
        },
        "subject":{
            "$ref":"#/definitions/Account_coverage"
        },
        "meta":{
            "$ref":"#/definitions/Account_meta"
        }
    },
    "description":""
}