version: '3'

services:
  lafia:
    image: lafia-service
    ports:
      - 9000
    labels:
      kompose.service.type: NodePort
    env_file: .env
    volumes:
      - .:/home/lafia-service
    networks:
      - main_network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: parallelscore
      POSTGRES_DB: parallelscoredb
      POSTGRES_PASSWORD: parallelscorepasswd
    ports:
      - 5432
    volumes:
      - ./.data/postgres-data:/var/lib/postgresql/data
    networks:
      - main_network

networks:
  main_network:
    driver: bridge
