import { ContainerModule } from 'inversify';
import TYPES from '../config/types';
import { AuthService } from './auth';
import { S3Service } from './aws';
import { CodeSystemService } from './codeSystems';
import { EmailService } from './email';
import { FhirServerService } from './fhirServer';
import { FileService } from './file';
import { LanguageService } from './lang';
import { LafiaMediaService } from './mediaServer';
import { RabbitMqService, RabbitMqSetup } from './messageBroker';
import { PatientService } from './patients';
import { PractitionerService } from './practitioners';
import { FhirResourceService, ImplementationGuideService } from './resources';
import { TwilioService } from './twilio';
import { UserService } from './users';
import { TwilioRoomService, VideoBroadcastService, VideoRecordService } from './videoRecords';

export const serviceModule = new ContainerModule((bind) => {
  bind<AuthService>(TYPES.AuthService).to(AuthService);
  bind<S3Service>(TYPES.S3Service).to(S3Service);
  bind<CodeSystemService>(TYPES.CodeSystemService).to(CodeSystemService);
  bind<EmailService>(TYPES.EmailService).to(EmailService);
  bind<FhirServerService>(TYPES.FhirServerService).to(FhirServerService);
  bind<FileService>(TYPES.FileService).to(FileService);
  // bind<KafkaSetup>(TYPES.KafkaSetup).to(KafkaSetup);
  // bind<KafkaService>(TYPES.KafkaService).to(KafkaService);
  bind<LanguageService>(TYPES.LanguageService).to(LanguageService);
  bind<LafiaMediaService>(TYPES.LafiaMediaService).to(LafiaMediaService);
  bind<PatientService>(TYPES.PatientService).to(PatientService);
  bind<PractitionerService>(TYPES.PractitionerService).to(PractitionerService);
  bind<FhirResourceService>(TYPES.FhirResourceService).to(FhirResourceService);
  bind<ImplementationGuideService>(TYPES.ImplementationGuideService).to(ImplementationGuideService);
  bind<TwilioService>(TYPES.TwilioService).to(TwilioService);
  bind<TwilioRoomService>(TYPES.TwilioRoomService).to(TwilioRoomService);
  bind<UserService>(TYPES.UserService).to(UserService);
  bind<VideoBroadcastService>(TYPES.VideoBroadcastService).to(VideoBroadcastService);
  bind<VideoRecordService>(TYPES.VideoRecordService).to(VideoRecordService);
  bind<RabbitMqService>(TYPES.RabbitMqService).to(RabbitMqService);
  bind<RabbitMqSetup>(TYPES.RabbitMqSetup).to(RabbitMqSetup);
});
