name: Build Process
on: 
  pull_request: 
    types: 
      - opened
      - synchronize
      - reopened
  push: 
    branches: 
      - dev 
jobs: 
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      
      - name: Install modules
        run: yarn install --ignore-engines
        env:
          TWILIO_ACCOUNT_SID: "${{ secrets.TWILIO_ACCOUNT_SID }}"
          TWILIO_AUTH_TOKEN: "${{ secrets.TWILIO_AUTH_TOKEN }}"
          TWILIO_API_KEY: "${{ secrets.TWILIO_API_KEY }}"
          TWILIO_API_SECRET: "${{ secrets.TWILIO_API_SECRET }}"
          TWILIO_VERIFY_SID: "${{ secrets.TWILIO_VERIFY_SID }}"
      - name: Run Test
        run: yarn test
      - 
        env: 
          SONAR_HOST_URL: "${{ secrets.SONAR_HOST_URL }}"
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
        uses: sonarsource/sonarqube-scan-action@master
      - 
        env: 
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
        timeout-minutes: 550
        uses: SonarSource/sonarqube-quality-gate-action@master
