name: Sonarqube Code Scanner
on: 
  pull_request: 
    types: 
      - opened
      - synchronize
      - reopened
  push: 
    branches: 
      - dev 
jobs: 
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps: 
      -
       uses: mattallty/jest-github-action@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         # this is just an example, this could be any command that will trigger jest
         test-command: "yarn test"
      - 
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - 
        env: 
          SONAR_HOST_URL: "${{ secrets.SONAR_HOST_URL }}"
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
        uses: sonarsource/sonarqube-scan-action@master
      - 
        env: 
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
        timeout-minutes: 550
        uses: SonarSource/sonarqube-quality-gate-action@master
